/** @type {import('ts-jest').JestConfigWithTsJest} */

// Mirrors the Vite `define` constants from vite.config.ts so that src/ can use
// __MODULE_VERSION__ / __BUILD_NUMBER__ instead of importing package.json and
// build-info.json. build-info.json is generated by `vite build`, so a fresh
// clone may not have it yet.
let buildNumber = 0;
try {
  buildNumber = require('./build-info.json').buildNumber ?? 0;
} catch {
  buildNumber = 0;
}

module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/tests'],
  testMatch: ['**/__tests__/**/*.+(ts|tsx|js)', '**/?(*.)+(spec|test).+(ts|tsx|js)'],
  transform: {
    '^.+\\.(ts|tsx)$': [
      'ts-jest',
      {
        tsconfig: {
          esModuleInterop: true,
          allowSyntheticDefaultImports: true
        }
      }
    ]
  },
  globals: {
    __MODULE_VERSION__: require('./package.json').version,
    __BUILD_NUMBER__: buildNumber
  },
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/types/**/*',
    '!src/main.ts', // Entry point with hooks - integration test territory
    // Abstract UI base class, currently 0% covered and with no dedicated suite.
    // This is the one remaining honest gap in the numbers below; drop this line
    // once base-trap-dialog.ts gets a suite of its own.
    '!src/dialogs/base-trap-dialog.ts'
    // NOTE: trap-dialog.ts and check-state-dialog.ts used to be excluded here
    // as "hard to unit test". Both now have dedicated suites
    // (tests/dialogs/trap-dialog.test.ts, tests/dialogs/check-state-dialog.test.ts)
    // so they are measured. combat-trap-dialog.ts and activating-trap-dialog.ts
    // were also listed - neither file has existed for some time.
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  // Ratchet, not an aspiration: these sit a couple of points under the actual
  // numbers as of v2.2.0 (61.57 stmts / 52.12 branch / 61.73 funcs / 62.54
  // lines) so ordinary churn does not redden CI but a real regression does.
  // Raise them as coverage improves - the goals in tests/README.md are
  // 80/75/80/80.
  coverageThreshold: {
    global: {
      statements: 60,
      branches: 50,
      functions: 60,
      lines: 61
    }
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  verbose: true
};
