name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

        **Note:** If you see any console errors (Press F12 in Foundry → Console tab), including them in your description is appreciated but not required.

  - type: input
    id: foundry-version
    attributes:
      label: Foundry VTT Version
      description: What version of Foundry VTT are you running?
      placeholder: "e.g., 13.330"
    validations:
      required: true

  - type: input
    id: dnd5e-version
    attributes:
      label: D&D 5e System Version
      description: What version of the D&D 5e system are you using?
      placeholder: "e.g., 4.0.0"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: |
        A clear description of the bug, including:
        - What you expected to happen
        - What actually happened
        - Any console errors (if applicable)
      placeholder: |
        When I create a trap with X option, I expected Y to happen, but instead Z occurred.

        Console showed: [error message if applicable]
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to Tile Manager
        2. Click 'Create Trap'
        3. Set option X to Y
        4. See error
    validations:
      required: true

  - type: textarea
    id: tile-actions
    attributes:
      label: Tile Actions (Screenshot or JSON)
      description: |
        **Very helpful:** Right-click the problematic tile → Export Tile → attach the JSON file here
        OR
        Screenshot of the tile's Monk's Active Tiles actions configuration
      placeholder: |
        Drag and drop the exported JSON file here, or paste screenshot
    validations:
      required: false
